listenport: 8080
viewdir: view
chiefadmin:
  0:
    email:  istvan.dombi@agl.group
    password: Scl181003
    superdmin: true
environment: local
db:
  environment:
    local:
      host: "localhost"
      name: "dadabasename"
      username: "databaseuser"
      password: "databasepassword"
  maxidleconns: 20
  maxopenconns: 20
  maxconnlifetimeminutes: 60
server:
  readtimeoutseconds: 20
  writetimeoutseconds: 20
  maxrps: 5
  banminutes: 10
  sessionkey: "sessionkey"
  banactive: false
  name: "Server Name"
mode:
  live: false
  debug: true
  rebuild_structure: false
  rebuild_data0: false
cache:
  enabled: false
adminrouter: admin
og:
  url: "http://www.domain.com"
  type: "website"
  title: "OG MyWebsite"
  description: "OG Description"
  image: "/opengraph/image/path.png"
ug:
  - value: "user_group1"
    label: "User Group 1"
    description: "User Group Description 1"
    default: true
  - value: "user_group2"
    label: "User Group 2"
    description: "User Group Description 2"
    default: false
  - value: "admin"
    label: "Admin"
    description: "Admin"
    default: false
  - value: "other"
    label: "Other (can not be classified)"
    description: "Other"
    default: false
language:
  allowed:
    - hu
    - en
notificationtargets: ["notificationtarget@mail.com"]