listenport: 8080
viewdir: view
chiefadmin:
  0:
    email:  istvan.dombi@agl.group
    password: Scl181003
    superdmin: true
environment: local
db:
  environment:
    local:
      host: "dbhost"
      name: "dbname"
      username: "dbuser"
      password: "dbpass"
  maxidleconns: 20
  maxopenconns: 20
  maxconnlifetimeminutes: 60
server:
  readtimeoutseconds: 20
  writetimeoutseconds: 20
  maxrps: 5
  banminutes: 10
  sessionkey: "sessionkey"
  banactive: false
  name: "Server Name"
mode:
  live: false
  debug: true
  rebuild_structure: true
  rebuild_data: false
cache:
  enabled: true
  type: "file"
  dir: "cache"
adminrouter: admin
og:
  url: "OG Url"
  type: website
  title: "Site Default Name"
  description: "Site Default Description"
  image: "/opengraph/default/image.png"
ug:
  - value: "usergroup1"
    label: "User Group 1"
    description: "User Group 1 Description"
    default: true
  - value: "usergroup2"
    label: "User Group 2"
    description: "User Group 2 Description"
    default: false
  - value: "admin"
    label: "Admin"
    description: "Admin"
    default: false
language:
  allowed:
    - hu
    - en