listenport: 8080
viewdir: view
chiefadmin:
  0:
    email:  istvan.dombi@agl.group
    password: Scl181003
    superdmin: true
environment: local
db:
  environment:
    local:
      host: "localhost"
      name: "baseadmin"
      username: "root"
      password: "NootNoot"
  maxidleconns: 20
  maxopenconns: 20
  maxconnlifetimeminutes: 60
server:
  readtimeoutseconds: 20
  writetimeoutseconds: 20
  maxrps: 5
  banminutes: 10
  sessionkey: "sessionkey"
  banactive: false
  name: "Server Name"
mode:
  live: false
  debug: true
  rebuild_structure: false
  rebuild_data: false
cache:
  enabled: true
  type: "file"
  dir: "view/cache"
adminrouter: admin
og:
  url: "OG Url"
  type: website
  title: "Site Default Name"
  description: "Site Default Description"
  image: "/opengraph/default/image.png"
language:
  allowed:
    - hu
    - en